# translate script configuration python project
project_folder: "."
docs_folder: "docs"
build_folder: "build"

# mkdocs migration
rst_folder: "source"
anchor_file: 'anchors.txt'
convert_folder: "migrate"
substitutions:
  project: MkDocs Translation Example
  author: Open Source Geospatial Foundation
  copyright: 2024, Open Source Geospatial Foundation
  project_copyright: 2024, Open Source Geospatial Foundation
extlinks:
  github: https://github.com/jodygarnett/translate/blob/main/%s
  tag: https://github.com/jodygarnett/translate/releases/tag/{{ release }}|Release {{ release }}
  squidfunk: https://squidfunk.github.io/mkdocs-material/%s
macro_ignore:
  - setup/index.md
nav:
  index.md: Home
  'translate/index.md': Translate
  'translate/migrate.md': Migrate
  guide/index.md: Guide

# markdown internationalization
deepl_base_url: "https://api-free.deepl.com"
upload_folder: "upload"
download_folder: "download"
