deepl_base_url: "https://api-free.deepl.com"
project_folder: "."
rst_folder: "source"
build_folder: "target"
docs_folder: "docs"
anchor_file: 'anchors.txt'
upload_folder: "translate"
convert_folder: "convert"
download_folder: "translate"
substitutions:
  project: GeoServer
  author: Open Source Geospatial Foundation
  copyright: 2023, Open Source Geospatial Foundation
  project_copyright: 2023, Open Source Geospatial Foundation